### ISSUE TITLE
Anforderungsheft mit Punkten befüllen

### ISSUE THREAD

**Issue by sam4ritan** [sam4ritan/kingfisher#4]
Benutzeroberfläche, Qualitätszielbestimmung, Globale Testszenarien/Testfälle, Entwicklungsumgebung

**Comment by sam4ritan** [comment]
Getan, aber noch keine Graphischen Darstellungen. Nachfragen, ob Pflichtenheft später noch aktualisiert werden kann/soll

**Comment by juha1996** [comment]
Anforderungsheft rausgesendet
